/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/car_renderd_default_modified.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.spacers.geometry}
        material={nodes.spacers.material}
        position={[-0.03, -0.36, -0.55]}
        rotation={[-0.01, 0, 0]}
        scale={[1.91, 1.91, 1.91]}
      />
      <group
        position={[-0.03, -0.36, -0.5]}
        rotation={[-0.01, 0, 0]}
        scale={[1.91, 1.91, 1.91]}
      >
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={nodes.Cylinder.material}
        />
        <mesh
          geometry={nodes.Cylinder_1.geometry}
          material={materials["front dots"]}
        />
      </group>
      <mesh
        geometry={nodes.plastic_pieece.geometry}
        material={nodes.plastic_pieece.material}
        position={[-0.03, 3.52, -0.52]}
        rotation={[-0.01, 0, 0]}
        scale={[1.91, 1.91, 1.91]}
      />
      <group
        position={[-0.03, -0.06, 0.15]}
        rotation={[-0.01, 0, 0]}
        scale={[1.91, 1.91, 1.91]}
      >
        <mesh
          geometry={nodes.Plane002.geometry}
          material={nodes.Plane002.material}
        />
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <group
        position={[-0.03, -0.36, -0.5]}
        rotation={[-0.01, 0, 0]}
        scale={[1.91, 1.91, 1.91]}
      >
        <mesh
          geometry={nodes.Plane005.geometry}
          material={nodes.Plane005.material}
        />
        <mesh
          geometry={nodes.Plane005_1.geometry}
          material={nodes.Plane005_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Tire_Cylinder009.geometry}
        material={nodes.Tire_Cylinder009.material}
        position={[1.03, 0.07, -2.29]}
        rotation={[1.57, 0, 0]}
        scale={[0.16, 0.19, 0.19]}
      />
      <mesh
        geometry={nodes.WheelBase_Cylinder001.geometry}
        material={nodes.WheelBase_Cylinder001.material}
        position={[1.06, 0.07, -2.29]}
        rotation={[1.57, 0, 0]}
        scale={[0.15, 0.19, 0.19]}
      />
      <mesh
        geometry={nodes.Tire_Cylinder001.geometry}
        material={nodes.Tire_Cylinder001.material}
        position={[1, 0.04, 1.36]}
        rotation={[1.57, 0, 0]}
        scale={[0.15, 0.18, 0.18]}
      />
      <mesh
        geometry={nodes.WheelBase_Cylinder002.geometry}
        material={nodes.WheelBase_Cylinder002.material}
        position={[1.03, 0.04, 1.36]}
        rotation={[1.57, 0, 0]}
        scale={[0.14, 0.18, 0.18]}
      />
      <mesh
        geometry={nodes.Tire_Cylinder002.geometry}
        material={nodes.Tire_Cylinder002.material}
        position={[-1.09, 0.07, -2.29]}
        rotation={[1.57, 0, 0]}
        scale={[0.16, 0.19, 0.19]}
      />
      <mesh
        geometry={nodes.WheelBase_Cylinder003.geometry}
        material={nodes.WheelBase_Cylinder003.material}
        position={[-1.12, 0.07, -2.29]}
        rotation={[1.57, 0, 0]}
        scale={[0.15, 0.19, 0.19]}
      />
      <mesh
        geometry={nodes.Tire_Cylinder003.geometry}
        material={nodes.Tire_Cylinder003.material}
        position={[-1.05, 0.04, 1.36]}
        rotation={[1.57, 0, 0]}
        scale={[0.15, 0.18, 0.18]}
      />
      <mesh
        geometry={nodes.WheelBase_Cylinder004.geometry}
        material={nodes.WheelBase_Cylinder004.material}
        position={[-1.08, 0.04, 1.36]}
        rotation={[1.57, 0, 0]}
        scale={[0.14, 0.18, 0.18]}
      />
      <group
        position={[-0.03, -0.36, -0.5]}
        rotation={[-0.01, 0, 0]}
        scale={[1.91, 1.91, 1.91]}
      >
        <mesh
          geometry={nodes.Plane006.geometry}
          material={nodes.Plane006.material}
        />
        <mesh
          geometry={nodes.Plane006_1.geometry}
          material={nodes.Plane006_1.material}
        />
      </group>
      <group position={[-0.03, -0.36, -0.5]} scale={1.16}>
        <mesh
          geometry={nodes.Cube_1.geometry}
          material={nodes.Cube_1.material}
        />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={nodes.Cube_2.material}
        />
        <mesh
          geometry={nodes.Cube_3.geometry}
          material={materials["front light strip["]}
        />
      </group>
      <mesh
        geometry={nodes.grill.geometry}
        material={nodes.grill.material}
        position={[-0.03, -0.39, -0.5]}
        rotation={[-0.01, 0, 0]}
        scale={[1.16, 1.36, 1.16]}
      />
      <mesh
        geometry={nodes.back_grill.geometry}
        material={nodes.back_grill.material}
        position={[-0.03, -0.38, 0.16]}
        rotation={[-0.01, 0, 0]}
        scale={[1.16, 1.36, 1.16]}
      />
      <mesh
        geometry={nodes.back_bumpers.geometry}
        material={nodes.back_bumpers.material}
        position={[-0.03, -0.36, -0.5]}
        rotation={[-0.01, 0, 0]}
        scale={1.16}
      />
      <mesh
        geometry={nodes.trunk.geometry}
        material={nodes.trunk.material}
        position={[-0.03, -0.36, -0.5]}
        scale={1.16}
      />
      <group position={[-0.03, -0.36, -0.5]} scale={1.16}>
        <mesh
          geometry={nodes.Cube019.geometry}
          material={nodes.Cube019.material}
          material-color="black"
          material-shininess="100"
        />
        <mesh
          geometry={nodes.Cube019_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[-0.03, -0.36, -0.5]} scale={1.16}>
        <mesh
          geometry={nodes.Cube021.geometry}
          material={nodes.Cube021.material}
          material-color="black"
          material-shininess="100"
        />
        <mesh
          geometry={nodes.Cube021_1.geometry}
          material={nodes.Cube021_1.material}
          material-color="black"
          shininess="100"
        />
      </group>
      <group position={[-0.03, -0.36, -0.5]} scale={1.16}>
        <mesh
          geometry={nodes.Cube023.geometry}
          material={nodes.Cube023.material}
        />
        <mesh
          geometry={nodes.Cube023_1.geometry}
          material={nodes.Cube023_1.material}
        />
      </group>
      <mesh
        geometry={nodes.TRUNK_SPACE.geometry}
        material={nodes.TRUNK_SPACE.material}
        position={[-0.03, 0.31, -0.5]}
        scale={1.16}
      />
      <mesh
        geometry={nodes.UNDER_LEFT_SEAT.geometry}
        material={materials["Material.008"]}
        position={[-0.03, -0.06, 0.19]}
        rotation={[0.02, 0, 0]}
        scale={[0.3, 0.43, 0.35]}
      />
      <group position={[-0.03, 0.23, 0.61]} scale={[1.05, 0.34, 0.34]}>
        <mesh
          geometry={nodes.Cube008.geometry}
          material={nodes.Cube008.material}
        />
        <mesh
          geometry={nodes.Cube008_1.geometry}
          material={nodes.Cube008_1.material}
        />
      </group>
      <group position={[-0.03, 0.44, -0.24]} scale={0.69}>
        <mesh
          geometry={nodes.Plane008.geometry}
          material={nodes.Plane008.material}
        />
        <mesh
          geometry={nodes.Plane008_1.geometry}
          material={materials["Material.019"]}
        />
      </group>
      <mesh
        geometry={nodes.STEERING_WHEEL.geometry}
        material={materials["Material.010"]}
        position={[0.47, 0.48, 0.35]}
        rotation={[0.09, 0, 0]}
        scale={[0.04, 0.04, 0.04]}
      />
      <mesh
        geometry={nodes.STEERING_WHEEL_SUPPORT.geometry}
        material={nodes.STEERING_WHEEL_SUPPORT.material}
        position={[0.47, 0.5, 0.44]}
        rotation={[-1.48, 0, 0]}
        scale={[0.03, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.STEERING_WHEEL_BASE.geometry}
        material={materials["Material.013"]}
        position={[0.47, 0.48, 0.35]}
        rotation={[1.66, 0, 0]}
        scale={[0.04, 0.04, 0.04]}
      />
      <mesh
        geometry={nodes.T_LOGO.geometry}
        material={nodes.T_LOGO.material}
        position={[-0.03, 0.25, 2.34]}
        rotation={[0.54, 0, 0]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.TESLA_LOGO.geometry}
        material={nodes.TESLA_LOGO.material}
        position={[0.88, 0.98, -3.21]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.TESLA_LOGO001.geometry}
        material={nodes.TESLA_LOGO001.material}
        position={[0.88, 3.91, -3.21]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.03}
      />
      <group position={[-0.03, -0.06, 0.19]} scale={[0.25, 0.2, 0.2]}>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.017"]}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials["Material.018"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-0.03, -0.06, 0.19]}
        scale={1.47}
      />
      <group
        position={[-0.03, -0.06, 0.19]}
        rotation={[1.51, 0, 0]}
        scale={[0.83, 0.83, 0.9]}
      >
        <mesh
          geometry={nodes.Plane021.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Plane021_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Plane021_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/car_renderd_default_modified.gltf");
